create database customer_behaviour;
use customer_behaviour;
select * from customer_data;

DESCRIBE customer_data;

ALTER TABLE customer_data CHANGE `Customer ID` customer_id BIGINT;
ALTER TABLE customer_data CHANGE `Age` age BIGINT;
ALTER TABLE customer_data CHANGE `Gender` gender TEXT;
ALTER TABLE customer_data CHANGE `Item Purchased` item_purchased TEXT;
ALTER TABLE customer_data CHANGE `Category` category TEXT;
ALTER TABLE customer_data CHANGE `Purchase Amount (USD)` purchase_amount BIGINT;
ALTER TABLE customer_data CHANGE `Location` location TEXT;
ALTER TABLE customer_data CHANGE `Size` size TEXT;
ALTER TABLE customer_data CHANGE `Color` color TEXT;
ALTER TABLE customer_data CHANGE `Season` season TEXT;
ALTER TABLE customer_data CHANGE `Review Rating` review_rating DOUBLE;
ALTER TABLE customer_data CHANGE `Subscription Status` subscription_status TEXT;
ALTER TABLE customer_data CHANGE `Shipping Type` shipping_type TEXT;
ALTER TABLE customer_data CHANGE `Discount Applied` discount_applied TEXT;
ALTER TABLE customer_data CHANGE `Promo Code Used` promo_code_used TEXT;
ALTER TABLE customer_data CHANGE `Previous Purchases` previous_purchases BIGINT;
ALTER TABLE customer_data CHANGE `Payment Method` payment_method TEXT;
ALTER TABLE customer_data CHANGE `Frequency of Purchases` frequency_of_purchases TEXT;

-- 1. what is the total revenue generated by male and female
select gender, sum(purchase_amount) as revenue 
from customer_data 
group by gender;

-- 2. which customers used a discount but still spent more than the average purchase amount?
select Customer_Id, purchase_amount
from customer_data
where discount_applied = 'yes' and purchase_amount >= (select avg(purchase_amount) from customer_data);

-- 3. Which are the top 5 products with the highest average review rating
select item_purchased, Round(avg(cast(review_rating as decimal(10,2))),2 )as "Average Product Rating"
from customer_data
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- 4. Compare the average purchase amounts between standard and express shipping.
select shipping_type,
avg(purchase_amount)
from customer_data
where shipping_type in('Standard','Express')
group by shipping_type;

-- 5. Do subscribed customers spend more? compare average spend and total revenue between subscribers and 
-- non-subscribers.
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer_data
group by subscription_status
order by total_revenue, avg_spend desc;

-- 6. Which 5 products have the highest percentage of purchases with discount applied?
SELECT item_purchased,
       ROUND(
           (SUM(CASE WHEN discount_applied = 'yes' THEN 1 ELSE 0 END) / COUNT(*)) * 100,
           2
       ) AS discount_rate
FROM customer_data
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- 7. Segment customers into new, returning, and loyal based on their total number of previous purchases, and show
-- the count of each segment. 
with customer_type as (
select customer_id, previous_purchases,
case 
	when previous_purchases = 1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'loyal'
    end as 'customer_segment'
from customer_data
)
select customer_segment, count(*) as "number of customers"
from customer_type
group by customer_segment;

-- 8. What are the top 3 most purchased products within each category?
WITH item_count AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer_data
    GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_count
WHERE item_rank <= 3;

-- 9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe/
select subscription_status,
count(customer_id) as repeat_buyers
from customer_data
where previous_purchases > 5
group by subscription_status;

describe customer_data;
-- 10. What is the revenue contribution of each group?
select age,
sum(purchase_amount) as total_revenue
from customer_data
group by age
order by total_revenue desc;